name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: unicorn.cr.cloud.ru/nest-server

      - name: Login to Cloud.ru Artifact Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: unicorn.cr.cloud.ru
          username: ${{ secrets.CLOUD_RU_ID }}
          password: ${{ secrets.CLOUD_RU_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
